### ISSUE TITLE
How do you add load indicator with real-time percentage value?

### ISSUE THREAD

**Issue by putuoka** [pSapien/theme#1]
Hello, how to add activity indicator with real-time percentage value when the button clicked and zip file downloaded?

**Comment by pSapien** [comment]
@putuoka 

`react-native-fs` gives the progress callback which you could listen and use the args like in the example to set the state. 

```typescript
 await RNFS.downloadFile({
    fromUrl: downloadLink,
    toFile: downloadedPath,
    begin: () => {},
    background: true,
    progressInterval: 0,
    progress: ({ bytesWritten, contentLength, jobId }) => {
      this.jobId = jobId;
      
      // you could use something like this to calculate the download progress in the UI.
      const downloadProgress = Math.floor((bytesWritten / contentLength) * 100);
      setProgressState(downloadProgress);
    },
  }).promise
```

**Comment by putuoka** [comment]
> @putuoka
> 
> `react-native-fs` gives the progress callback which you could listen and use the args like in the example to set the state.
> 
> ```ts
>  await RNFS.downloadFile({
>     fromUrl: downloadLink,
>     toFile: downloadedPath,
>     begin: () => {},
>     background: true,
>     progressInterval: 0,
>     progress: ({ bytesWritten, contentLength, jobId }) => {
>       this.jobId = jobId;
>       
>       // you could use something like this to calculate the download progress in the UI.
>       const downloadProgress = Math.floor((bytesWritten / contentLength) * 100);
>       setProgressState(downloadProgress);
>     },
>   }).promise
> ```

Thank you very much

**Comment by putuoka** [comment]
Hi @pSapien How to keep the changes even after the apps is closed? i mean like save it in asyncstorage.

**Comment by pSapien** [comment]
@putuoka What do you want to save in AsyncStorage?

**Comment by putuoka** [comment]
> @putuoka What do you want to save in AsyncStorage?

Sorry what I mean when I reopen the app the theme changes or updates remain. For now when the bollywood theme is selected it changes but when the application is closed and reopened the theme returns to normal and must be updated again.

**Comment by pSapien** [comment]
> > @putuoka What do you want to save in AsyncStorage?
> 
> Sorry what I mean when I reopen the app the theme changes or updates remain. For now when the bollywood theme is selected it changes but when the application is closed and reopened the theme returns to normal and must be updated again.

- Store the path of the selected theme to the async storage or the id, when the app is reopened, you could use that to retrieve the selected theme

**Comment by pSapien** [comment]
@putuoka Closing this as the query seems to be answered. Please feel free to open another issue if need be.
